name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:

  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies for client
        run: |
          cd client
          npm install --force

      - name: Check style for client
        run: |
          cd client
          npm run lint

      - name: Install dependencies for server
        run: |
          cd server
          npm install

      - name: Check style for server
        run: |
          cd server
          npm run lint
