name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    
permissions: read-all|write-all

jobs:

  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies for client
        run: |
          cd client
          npm install --force

      - name: Check style for client
        run: |
          cd client
          npm run lint

      - name: Install dependencies for server
        run: |
          cd server
          npm install

      - name: Check style for server
        run: |
          cd server
          npm run lint

      - name: Trigger deployment
        if:  ${{ success() }} && ${{ github.event_name == 'push' }}
        run: |
          curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API }}
  tag_release:
      needs: [simple_deployment_pipeline]
      runs-on: ubuntu-20.04
      steps:
      
       - name: Bump version and push tag
         uses: anothrNick/github-tag-action@1.55.0
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
